<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\pantheon_advanced_page_cache\ClearEdgePaths;

/**
 * Implements hook_file_update().)
 */
function pantheon_advanced_page_cache_file_update(EntityInterface $file) {
  // Don't try this if we're not in a Pantheon environment.
  if (!function_exists('pantheon_clear_edge_paths')) {
    return;
  }
  ClearEdgePaths::file($file);
}
