<?php
/**
 * @file
 * Provides testing functionality.
 */

/**
 * Implements hook_pre_emit_cache_tags_alter().
 */
function pantheon_advanced_page_cache_test_pre_emit_cache_tags_alter(&$tags) {
  // This is a contrived example of how custom code can be used
  // to limit a giant list of tags.
  // In this case, automated Behat tests generate nodes
  // tagged in 100s of taxonomy terms each. Then when
  // those nodes are rendered on a view like frontpage
  // they result in too many total surrogate-keys being set.
  if (in_array("views:frontpage.page", $tags)) {
    $new_tags = array();
    foreach ($tags as $tag) {
      if (strpos($tag, "taxonomy_term:") === FALSE) {
        $new_tags[] = $tag;
      }
    }
    $tags = $new_tags;
  }
}

/**
 * Implements hook_entity_update().
 */
function pantheon_advanced_page_cache_test_entity_presave($entity, $entity_type) {
$tids_to_clear = [];
  if (!empty($entity->field_tags[LANGUAGE_NONE][0]['tid'])) {
    foreach($entity->field_tags[LANGUAGE_NONE] as $field_value) {
      if (!empty($field_value['tid'])) {
        $tids_to_clear[] = 'taxonomy_term:' . $field_value['tid'];
      }
    }
  }
  drupal_invalidate_cache_tags($tids_to_clear);
}
